config/routes.rb
Secretsanta::Application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" } 
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: "login"
    delete "logout", to: "devise/sessions#destroy", as: "logout"
    get "signup", to: "users/registrations#new", as: "signup"
    resources :groups, path: "/", only: :none do
      get "signup", to: "users/registrations#new", as: "signup"
    end
  end

  get "about", to: "pages#about", as: :about
  get "tips", to: "pages#tips", as: :tips
  get "2013", to: "pages#blog_roll", as: :blog_roll
  get "run-group", to: "pages#run_group", as: :run_group
  get "open-groups", to: "pages#groups", as: :groups_page

  put "enquiry", to: "groups#enquiry", as: :enquiry_group

  
  namespace :santa do
    get "/", to: "groups#index", as: "root"
    resources :groups do
      resources :content, :matches
      resources :users, only: :none do
        collection do
          get "assign"
          put "set_assignments"
        end
      end
    end
    resources :users, only: [:show, :index]
    resources :messages, only: [:new, :create]
  end

  namespace :elves do
    get "/", to: "groups#show"
    # resources :content, only: [:index, :show, :edit, :update]
    resources :users do
      member do
        put "remove"
        put "replace"
        get "pull_out"
      end
    end
  end

  resources :groups, path: "/", only: :show do
    # get "/signup", to: "devise/registrations#new", as: "signup"
    resources :content, path: "gifts", only: [:show, :new, :edit, :update, :index] do
      member do
        put "edit", to: "content#update"
        put "send_gift"
        get "export"
        get "upload"
        patch "import"
        get "export"
        get "publish"
        put "save_publish"
      end
    end
  end
  resources :users

  root to: "pages#home"
end

app/models/group.rb
class Group < ActiveRecord::Base
	include Tokenfindable

	has_many :matches
	has_many :content
	has_many :users

	enum status: { open: 0, matched: 1, gifted: 2, closed: 3, retired: 4 }

	MATCH_TIME = Time.utc(Time.now.year, 12, 05)
	GIFT_TIME = Time.utc(Time.now.year, 12, 25)

	validates :name, presence: true
	validates :slug, presence: true, format: { with: /\A[a-zA-Z\-]+\z/, message: "can only have letters and -" }
	validates :status, presence: true

	def to_param
		slug
	end

	def self.current_id=(id)
    Thread.current[:group_id] = id
  end
  
  def self.current_id
    Thread.current[:group_id]
  end

	def year
		gift_time.strftime("%Y")
	end

	def self.create_matches
		logger.info "Starting to create matches for all open groups"
		count = 0
		open.each do |group|
			group.create_matches
			count += 1
	 	end
	 	logger.info "Finished creating matches for #{count} groups"
	end

	def create_matches
		logger.info "Starting to create matches for the #{self.name} group"
		users = User.available.where(group: self)
		count = 0
		if users.length > 2
			matches = loop do
	      shuffled = users.shuffle.zip(users.shuffle)
	      break shuffled if shuffled.index { |x,y| x == y } == nil
	    end
	    matches.each do |match|
	    	giver = match[0]
	    	receiver = match[1]
	    	Match.create(group: self, giver: giver, receiver: receiver)
				UserMailer.match_notification(giver, receiver).deliver_later
				count += 1
	    end
	    self.matched!
	  else
	  	print "Not enough available users in the #{group.name} group. Need at least 3."
	  end
	  logger.info "Finished creating #{count} matches the #{self.name} group"
	end

	def self.give_gifts
		logger.info "Starting to deliver gifts for all matched groups"
		count = 0
		Group.matched.each do |group|
			group.give_gifts
			count += 1
		end
		logger.info "Finished delivering gifts for #{count} groups"
	end

	def give_gifts
		logger.info "Starting to deliver gifts for the #{self.name} group"
		matches = Match.includes(:giver, :receiver).where(group_id: self.id)
		sent = 0
		missed = 0
		matches.each do |match|
			content = Content.find_by(match: match)
			if match.receiver && content && content.body
				content.given!
				UserMailer.send_gift(match.receiver, content, self).deliver_later
				sent += 1
			elsif match.receiver && match.giver
				UserMailer.no_gift_from_you(match.giver, match.receiver).deliver_later
				UserMailer.no_gift_for_you(match.receiver).deliver_later
				missed += 1
			end
		end
		self.gifted!
		logger.info "Finished #{sent} delivering gifts with #{missed} missing out for the #{self.name} group"
	end

	def draw_time
		if open?
			Group::MATCH_TIME
		elsif matched?
			Group::GIFT_TIME
		end
	end
end

app/controllers/elves/groups_controller.rb
class Elves::GroupsController < Elves::ElvesController

	def show
		@group = current_tenant
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.send(params[:filter]).includes(:giver, receiver_match: :content).order(:name)
		else
			@users = User.includes(:giver, receiver_match: :content).order(:name)
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  prepend_before_action :set_group
  
  def show
    if @group.open? || @group.closed?
      @users = User.available.order(created_at: :desc)
    elsif @group.matched? || @group.gifted?
      @users = User.playing.order(created_at: :desc)
    end
    if @group.gifted? || @group.closed?
      @content = Content.published
    end
  end

  def enquiry
    GroupMailer.enquiry(params[:group], params[:email]).deliver_later
  end

  private

    def set_group
      @current_tenant = @group = Group.find_by(slug: params[:id])
    end
end

app/controllers/santa/groups_controller.rb
class Santa::GroupsController < Santa::SantaController
	skip_around_action :scope_current_tenant
	before_action :find_group_by_slug, only: [:show, :edit, :update]

	def index
		@groups = Group.includes(:users)
	end

	def show
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.send(params[:filter]).includes(:giver).where(group: @group).order(:name)
		else
			@users = User.includes(:giver).where(group: @group).order(:name)
		end
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			flash[:success] = "#{@group.name} has been created."
			redirect_to edit_santa_group_path(@group)
		else
			flash_errors(@group, true)
			puts flash.inspect
			render :new
		end
	end

	def edit
	end

	def update
		if @group.update(group_params)
			flash[:success] = "Those updates have been saved"
			redirect_to edit_santa_group_path(@group)
		else
			flash_errors(@group, true)
			puts flash.inspect
			render :edit
		end
	end

	private

		def find_group_by_slug
			@group = Group.find_by(slug: params[:id])
		end

		def group_params
			params.require(:group).permit(:name, :slug, :status)
		end
end

app/views/groups/_gifted.html.erb
<% if !current_user.receiver_match.content || (current_user.receiver_match.content && !current_user.receiver_match.content.given?) %>
	<h3><strong><%= link_to current_user.receiver.name, current_user.receiver.blog, target: "_blank" %></strong> is still waiting on your gift</h3>
	<%= link_to "Work on your content gift", new_group_content_path(group), class: "csw-button csw-contrast-button" %> <p>It's not too late. You can still send <%= current_user.receiver.first_name %> a gift.</p>
	<p><br /></p>
<% end %>

<h2><%= Content.published.count %> of <%= Match.count %> gifts are online now.</h2>
<% if gift %>
	<%= link_to "Pick up your gift", group_content_path(group, gift), class: "csw-button" %>
	<% if gift.url.blank? %>
		<p>Once you've published your gift, you can add its link to the year's blog roll.</p>
		<%= link_to "List your published gift", publish_group_content_path(group, gift), class: "csw-button", remote: true %>
	<% end %>
<% else %>
	<p>Your gift is still being worked on (hopefully).</p>
<% end %>

app/views/groups/_matched.html.erb
<h3>Your match is <strong><%= link_to match.name, match.blog, target: "_blank" %></strong></h3>
<%= link_to "Work on your content gift", new_group_content_path(group), class: "csw-button" %> <p>You can save your work and come back any time.</p>

app/views/groups/enquiry.js.erb
$('.enquiry-form').remove();
$('body').append('<%=j render 'layouts/modal' %>');
$('#csw-modal-window').modal('show');
$('.csw-modal-main-wrapper').html("<div class='csw-modal-body'>"
                                  + "<i class='csw-icon csw-icon-thumbs-up csw-font-green csw-icon-giant'></i>"
                                  + "<h2 class='csw-finished-heading'>Nice! We've let Santa know you're interested.</h2>"
                                  + "<p>He'll get in touch soon about the <%= params[:group] %> group. You can close this window and get back to your day.</p>"
                                  + "</div>");
$('.csw-modal-title').html("&nbsp;");

app/views/groups/show.html.erb
<% title group_title(@group) %>

<div class="row">
	<div class="small-12 columns">
		<h1><%= yield :heading %></h1>
	</div>
</div>
<div class="row">
	<div class="small-12 columns">
		<%= CountdownPresenter.new(@group, self).render_countdown %>
		<%= GroupStatePresenter.new(@group, current_user, self).render_intro %>
		<% if @group.open? || @group.matched? %>
			<h3>Here are the good children</h3>
			<div class="row csw-item-rows users">
	      <% @users.each do |user| %>
	    		<%= render "users/user", user: user, display_email: false %>
	    	<% end %>
	    </div>
	  <% else %>
	  	<p>The blog roll is below. To share it publicly, use this link: <%= link_to group_content_index_url(@group), group_content_index_url(@group), target: "_blank" %></p>
	  	<% if @content.present? %>
        <ul class="all_content">
          <% @content.each do |content| %>
            <%= render "content/content_published", content: content %>
          <% end %>
        </ul>
      <% else %>
        <p>Check back soon.</p>
      <% end %>
	  <% end %>
	</div>
</div>