config/routes.rb
Secretsanta::Application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" } 
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: "login"
    delete "logout", to: "devise/sessions#destroy", as: "logout"
    get "signup", to: "users/registrations#new", as: "signup"
    resources :groups, path: "/", only: :none do
      get "signup", to: "users/registrations#new", as: "signup"
    end
  end

  get "about", to: "pages#about", as: :about
  get "tips", to: "pages#tips", as: :tips
  get "2013", to: "pages#blog_roll", as: :blog_roll
  get "run-group", to: "pages#run_group", as: :run_group
  get "open-groups", to: "pages#groups", as: :groups_page

  put "enquiry", to: "groups#enquiry", as: :enquiry_group

  
  namespace :santa do
    get "/", to: "groups#index", as: "root"
    resources :groups do
      resources :content, :matches
      resources :users, only: :none do
        collection do
          get "assign"
          put "set_assignments"
        end
      end
    end
    resources :users, only: [:show, :index]
    resources :messages, only: [:new, :create]
  end

  namespace :elves do
    get "/", to: "groups#show"
    # resources :content, only: [:index, :show, :edit, :update]
    resources :users do
      member do
        put "remove"
        put "replace"
        get "pull_out"
      end
    end
  end

  resources :groups, path: "/", only: :show do
    # get "/signup", to: "devise/registrations#new", as: "signup"
    resources :content, path: "gifts", only: [:show, :new, :edit, :update, :index] do
      member do
        put "edit", to: "content#update"
        put "send_gift"
        get "export"
        get "upload"
        patch "import"
        get "export"
        get "publish"
        put "save_publish"
      end
    end
  end
  resources :users

  root to: "pages#home"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :omniauthable

  # include DeviseOverrideable
	include Tokenfindable
	include Tenantable

	scope :available, -> { where(available: true).where.not(email: nil, blog: nil, name: nil) }
	scope :unavailable, -> { where("available != true OR email IS NULL OR blog IS NULL OR name IS NULL") }
	scope :playing, -> { available.joins(:receiver_match) }
	scope :waiting_list, -> { available.joins("LEFT OUTER JOIN matches ON users.id = matches.receiver_id OR users.id = matches.giver_id").where("matches.receiver_id IS NULL OR matches.giver_id IS NULL") }
  scope :gave_gift, -> { playing.joins("INNER JOIN content ON matches.id = content.match_id").where("content.body is not null AND content.status = ?", Content.statuses["given"]) }
  scope :no_gift_given, -> { playing.joins("LEFT OUTER JOIN content on matches.id = content.match_id").where("content.id IS NULL OR content.status != ?", Content.statuses["given"]) }
  scope :waiting_for_gift, -> { available.joins(:giver_match).joins("LEFT OUTER JOIN content on matches.id = content.match_id").where("content.id IS NULL OR content.status != ?", Content.statuses["given"]) }

	before_create :set_defaults

	has_one :giver_match, class_name: "Match", foreign_key: "receiver_id"
	has_one :giver, through: :giver_match, class_name: "User"
	has_one :receiver_match, class_name: "Match", foreign_key: "giver_id"
	has_one :receiver, through: :receiver_match, class_name: "User"

	validates :name, presence: true, on: :update
	validates :blog, presence: true, on: :update
	validates :group_id, presence: true, on: :update
	validates :email, presence: true, on: :update

	enum role: { blogger: 0, elf: 1, santa: 2 }

	def blog=(value)
		unless value && value.index(/https?:\/\//)
			value = "http://#{value}"
		end

		write_attribute(:blog, value)
	end

	def self.with_omniauth(auth, params = nil)
	  unscoped.where(provider: auth["provider"], uid: auth["uid"]).first_or_initialize do |user|
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth["info"]["name"]
	    user.email = auth["info"]["email"]
	    user.image = auth["info"]["image"]
	    user.location = auth["info"]["location"]
	    # user.blog = auth["info"]["urls"]["Website"] ? Unshorten[auth["info"]["urls"]["Website"]] : auth["info"]["urls"]["Twitter"]
	    user.group = Group.find_by(slug: params["group"]) if params
	  end
	end

	def self.valid_scope?(scope)
		["all", "available", "unavailable", "playing", "waiting_list", "gave_gift", "no_gift_given", "waiting_for_gift"].include?(scope)
	end

	def self.statuses(group_status)
		case group_status
		when "open"
			%w(available unavailable)
		when "matched"
			%w(playing waiting_list unavailable)
		when "gifted"
			%w(gave_gift no_gift_given waiting_for_gift)
		end
	end

	def available?
		available && !incomplete_profile?
	end

	def playing?
		giver_match && available?
	end

	def waiting?
		!giver_match && available?
	end

	def gave_gift?
		receiver_match && receiver_match.content && receiver_match.content.given?
	end

	def no_gift_given?
		receiver_match && (!receiver_match.content || !receiver_match.content.given?)
	end

	def waiting_for_gift?
		giver_match && (giver_match.content.blank? || !giver_match.content.given?)
	end

	def playing_status(group_status)
		if group_status == "matched"
			if playing?
				"playing"
			elsif waiting?
				"waiting"
			elsif incomplete_profile?
				"incomplete"
			elsif !available?
				"unavailable"
			end
		elsif group_status == "gifted"
			if gave_gift?
				"gave_gift"
			elsif no_gift_given?
				"no_gift_given"
			else
				""
			end
		else
			if available?
				"available"
			elsif incomplete_profile?
				"incomplete"
			elsif !available?
				"unavailable"
			end
		end
	end

	def first_name
    name.split(' ')[0]
  end

  def incomplete_profile?
  	!(email && blog && name && group_id)
  end

  def writer?(content)
  	@writer ||= self.id == content.match.giver_id
  end

  # def giver
  # 	User.find_by(id: Match.find_by(receiver_id: self.id))
  # end

  # def receiver
  # 	User.find_by(id: Match.find_by(giver_id: self.id))
  # end

  private

  	def set_defaults
  		self.available = true
  		self.role = User.roles[:blogger] if self.role.nil?
  	end
end

app/controllers/elves/users_controller.rb
class Elves::UsersController < Elves::ElvesController
  before_action :find_user_by_token, only: [:show, :edit, :update, :pull_out, :remove, :replace]

	def show
	end

	def edit
  end

  def update
  	respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, flash: { success: "That update has been saved successfully" }}
        format.js { render js: "window.location = '#{admin_account_path(@account)}'" }
      else
        format.html { 
          flash_errors(@account)
          render 'new'
        }
        format.js
      end
    end
  end

  def pull_out
  end

  def remove
    @user.giver.receiver = @user.receiver
    @user.receiver_match.delete
    @user.update(available: false)
    flash[:success] = "#{@user.name} has been removed from this year's secret santa"
    redirect_to elves_path
  end

  def replace
    @replacement = User.find_by(token: params[:replacement])
    @user.giver.receiver = @user.receiver.giver = @replacement
    @user.update(available: false)
    flash[:success] = "#{@user.name} has been replaced by #{@replacement.name} for this year's secret santa"
    redirect_to elves_path
  end

  private

    def find_user_by_token
      @user = User.find_by(token: params[:id])
    end

  	def user_params
      params.require(:user).permit(:name, :email, :blog, :location)
    end
end

app/controllers/santa/content_controller.rb
class Santa::ContentController < ApplicationController
  before_action :find_group_by_slug, only: [:index, :show, :edit, :update]
  before_action :find_content_by_token, only: [:show, :edit, :update]

  def index
    @content = Content.where(group: @group)
  end

  def show
  end

  def edit
  end

  def update
    unless !@content.update(content_params)
      flash_errors(@content)
    end
    redirect_to santa_group_content_path(@group, @content)
  end

  private

    def content_params
      params.require(:content).permit(:title, :url, :status)
    end

    def find_content_by_token
      @content = Content.find_by(token: params[:id])
    end

    def find_group_by_slug
      @group = Group.find_by(slug: params[:group_id])
    end
end

app/controllers/santa/groups_controller.rb
class Santa::GroupsController < Santa::SantaController
	skip_around_action :scope_current_tenant
	before_action :find_group_by_slug, only: [:show, :edit, :update]

	def index
		@groups = Group.includes(:users)
	end

	def show
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.send(params[:filter]).includes(:giver).where(group: @group).order(:name)
		else
			@users = User.includes(:giver).where(group: @group).order(:name)
		end
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			flash[:success] = "#{@group.name} has been created."
			redirect_to edit_santa_group_path(@group)
		else
			flash_errors(@group, true)
			puts flash.inspect
			render :new
		end
	end

	def edit
	end

	def update
		if @group.update(group_params)
			flash[:success] = "Those updates have been saved"
			redirect_to edit_santa_group_path(@group)
		else
			flash_errors(@group, true)
			puts flash.inspect
			render :edit
		end
	end

	private

		def find_group_by_slug
			@group = Group.find_by(slug: params[:id])
		end

		def group_params
			params.require(:group).permit(:name, :slug, :status)
		end
end

app/controllers/santa/messages_controller.rb
class Santa::MessagesController < Santa::SantaController

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params).deliver_later
		if @message.errors.full_messages.present?
			flash.now[:error] = @message.errors.full_messages.first
			render 'new'
		else
			flash[:success] = "Message was sent"
			redirect_to santa_root_path
		end
	end

	private

		def message_params
			params.require(:message).permit(:to, :subject, :body, :template)
		end
end

app/controllers/santa/santa_controller.rb
class Santa::SantaController < ApplicationController
	# layout 'santa'

	skip_before_action :authorize, :check_profile
	before_action :authorize_santa

	private 

		def authorize_santa
			deny_access unless current_user.santa?
		end

end

app/controllers/santa/users_controller.rb
class Santa::UsersController < Santa::SantaController
	before_action :find_user_by_token, only: [:show, :edit, :update]
	before_action :find_group_by_slug, only: [:assign, :set_assignments]

	def index
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.unscoped.send(params[:filter]).includes(:group).order(:name)
		else
			@users = User.unscoped.includes(:group)
		end
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "#{@user.name} has been created."
			redirect_to edit_user_path(@user)
		else
			flash_errors(@user, true)
			puts flash.inspect
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Those updates have been saved"
			redirect_to edit_user_path(@user)
		else
			flash_errors(@user, true)
			puts flash.inspect
			render :edit
		end
	end

	def assign
		if params[:search]
			@users = User.unscoped.includes(:group).where("name like :search or email like :search", search: "%#{params[:search]}%")
		end
	end

	def set_assignments
		@user = User.find_by(email: params[:email])
		if @user
			if @user.update(role: User.roles[:elf], group: @group)
				flash[:success] = "#{@user.name} has been elfed"
				UserMailer.made_elf(@user, @group).deliver_later
				redirect_to assign_santa_group_users_path(@group)
			else
				flash_errors(@user, true)
				render :assign
			end
		else
			flash[:success] = "An invite email has been sent to #{params[:email]}"
			UserMailer.invited_elf(params[:email], @group).deliver_later
			redirect_to assign_santa_group_users_path(@group)
		end
	end

	private

		def find_user_by_token
			@user = User.unscoped.find_by(token: params[:id])
		end

		def find_group_by_slug
			@group = Group.find_by(slug: params[:group_id] || params[:id])
		end

		def user_params
			params.require(:user).permit(:name, :slug)
		end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_filter :configure_permitted_parameters

  def new
    build_resource({})
    resource.group = Group.find_by(slug: params[:group_id])
    respond_with self.resource
  end

  protected

  	def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) do |u|
	      u.permit(:email, :password, :password_confirmation, :group_id)
	    end
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_profile, only: [:edit, :update]
  before_action :find_user, only: [:show, :edit, :update, :email, :set_email, :destroy]
  before_action :authorize, only: [:edit, :update, :email, :set_email, :destroy]

  def index
    @users = User.available.order(created_at: :asc)
  end

  def show
  end

  def edit
  end

  def update
    was_incomplete = @user.incomplete_profile?
  	if @user.update_attributes(user_params)
      if was_incomplete
        flash[:success] = "Great! Your profile is complete and you're ready for Blog Secret Santa"
        UserMailer.welcome(@user).deliver_later
        redirect_to group_path(@user.group)
      else
        flash[:success] = "Updated without a hitch!"
  		  redirect_to edit_user_path(@user)
      end
  	else
      flash[:error] = @user.errors.full_messages
  		render "edit"
  	end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    flash[:success] = "Well, you went removed yourself. Now it's just you against the world."
    redirect_to root_path
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :blog, :available, :group_id, :location)
  	end

    def find_user
      @user = User.find_by(token: params[:id])
    end

    def authorize
      unless @user == current_user
        flash[:error] = "You don't have access."
        redirect_to root_path
      end
    end
end

app/views/santa/users/_elf.html.erb
<p><%= link_to elf.name, santa_group_user_path(group, elf) %></p>

app/views/santa/users/_user.html.erb
<div class="small-12 medium-6 large-4 columns csw-item-row csw-hover user full <%= user.playing_status(group.status) if group %>">
	<%= link_to santa_user_path(user), class: "csw-avatar-link" do %>
		<%= gravatar_for(user) %>
	<% end %>
	<div class="csw-item-row-content csw-indent">
		<div class="user-name"><%= link_to user.name.blank? ? "No name" : user.name, santa_user_path(user) %></div>
		<div class="group-name"><%= user.group.name if user.group %></div>
		<div class="user-email"><i class="csw-icon csw-icon-envelope-o"></i> <%= user.email %></div>
		<div class="user-blog"><i class="csw-icon csw-icon-pencil"></i> <%= link_to host_only(user.blog), user.blog, target: "_blank" if user.blog %></div>
		<% unless user.location.blank? %>
			<div class="user-location"><i class="csw-icon csw-icon-map-marker"></i> <%= user.location %></div>
		<% end %>
		<% if group %>
			<div class="csw-meta">
				<span class="playing-status"><%= user.playing_status(group.status).humanize %></span>
			</div>
		<% end %>
	</div>
</div>

app/views/santa/users/_user_summaries.html.erb
    <div class="user-summaries row">
      <div class="small-6 medium-3 columns">
        <%= link_to santa_users_path do %>
          <div class="user-summary total">
            <span class="user-count"><%= User.count %></span>
            <span class="user-name">
              <span class="csw-icon csw-icon-user"></span> Total registered
            </span>
          </div>
        <% end %>
      </div>
      <% User.statuses(group_status).each do |status| %>
	      <div class="small-6 medium-3 columns">
	        <%= link_to santa_users_path(filter: status) do %>
	          <div class="user-summary <%= status %>">
	            <span class="user-count"><%= User.send(status).size %></span>
	            <span class="user-name">
	              <span class="csw-icon csw-icon-user"></span> <%= status.humanize %>
	            </span>
	          </div>
	        <% end %>
	      </div>
	    <% end %>
    </div>

app/views/santa/users/assign.html.erb
<% title "Assign elves to #{@group.name}" %>

<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<div class="content center">
				<h1><%= yield :heading %></h1>
			</div>
			<h2>Current elves</h2>
			<% @group.users.elf.each do |elf| %>
				<%= render "santa/users/elf", group: @group, elf: elf %>
			<% end %>
			<p>&nbsp;</p>
			<%= form_tag assign_santa_group_users_path(@group), method: :get, class: "form-inline" do %>
				<div class="form-group">
					<%= text_field_tag :search, "", class: "form-control" %>
				</div>
				<%= submit_tag "Search for elves", class: "btn btn-default" %>
			<% end %>

			<% if @users %>
				<h3>Found users</h3>
				<p>Copy the email address of the one you want to add as an elf to the <%= @group.name %> group.
				<ul>
					<% @users.each do |user| %>
						<li><%= "#{user.name} #{user.email}" %> - Group: <%= user.group.name if user.group %></li>
					<% end %>
				</ul>
			<% end %>

			<p>&nbsp;</p>
			<%= form_tag set_assignments_santa_group_users_path(@group), method: :put do %>
				<p>Enter the email address for the person you want to add as an elf to the <%= @group.name %> group.
				<div class="form-group">
					<%= text_field_tag :email, "", class: "form-control", placeholder: "Email address" %>
				</div>
				<%= submit_tag "Add elf", class: "btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>

app/views/santa/users/index.html.erb
<% title "List of users" %>

<div class="row">
	<div class="small-12 columns">
		<h1><%= yield :heading %></h1>
		<div class="row csw-item-rows users">
      <% @users.each do |user| %>
      	<%= render "santa/users/user", user: user, group: user.group %>
      <% end %>
    </div>
	</div>
</div>

app/views/santa/users/show.html.erb
<% title @user.name.present? ? @user.name : "No name" %>

<div class="row">
	<div class="small-12 columns">
	<div class="csw-item-row user full <%= @user.playing_status(@user.group.status) if @user.group %>">
		<h2><%= yield :heading %> is <span class="playing-status"><%= @user.group ? @user.playing_status(@user.group.status).humanize : "Incomplete" %></span></h2>
		<%= gravatar_for(@user) %>
		<div class="csw-item-row-content csw-indent">
			<div class="user-email"><%= @user.email %></div>
			<div class="user-blog"><%= link_to @user.blog, @user.blog, target: "_blank" if @user.blog %></div>
			<% unless @user.location.blank? %>
				<div class="user-location"><span class="glyphicon glyphicon-map-marker"></span> <%= @user.location %></div>
			<% end %>
			<div class="csw-meta">
				Joined <%= time_ago_in_words(@user.created_at) %> ago<br />
				Last updated <%= time_ago_in_words(@user.updated_at) %> ago
			</div>
		</div>
	</div>
</div>