config/routes.rb
Secretsanta::Application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" } 
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: "login"
    delete "logout", to: "devise/sessions#destroy", as: "logout"
    get "signup", to: "users/registrations#new", as: "signup"
    resources :groups, path: "/", only: :none do
      get "signup", to: "users/registrations#new", as: "signup"
    end
  end

  get "about", to: "pages#about", as: :about
  get "tips", to: "pages#tips", as: :tips
  get "2013", to: "pages#blog_roll", as: :blog_roll
  get "run-group", to: "pages#run_group", as: :run_group
  get "open-groups", to: "pages#groups", as: :groups_page

  put "enquiry", to: "groups#enquiry", as: :enquiry_group

  
  namespace :santa do
    get "/", to: "groups#index", as: "root"
    resources :groups do
      resources :content, :matches
      resources :users, only: :none do
        collection do
          get "assign"
          put "set_assignments"
        end
      end
    end
    resources :users, only: [:show, :index]
    resources :messages, only: [:new, :create]
  end

  namespace :elves do
    get "/", to: "groups#show"
    # resources :content, only: [:index, :show, :edit, :update]
    resources :users do
      member do
        put "remove"
        put "replace"
        get "pull_out"
      end
    end
  end

  resources :groups, path: "/", only: :show do
    # get "/signup", to: "devise/registrations#new", as: "signup"
    resources :content, path: "gifts", only: [:show, :new, :edit, :update, :index] do
      member do
        put "edit", to: "content#update"
        put "send_gift"
        get "export"
        get "upload"
        patch "import"
        get "export"
        get "publish"
        put "save_publish"
      end
    end
  end
  resources :users

  root to: "pages#home"
end

app/models/group.rb
class Group < ActiveRecord::Base
	include Tokenfindable

	has_many :matches
	has_many :content
	has_many :users

	enum status: { open: 0, matched: 1, gifted: 2, closed: 3, retired: 4 }

	MATCH_TIME = Time.utc(Time.now.year, 12, 05)
	GIFT_TIME = Time.utc(Time.now.year, 12, 25)

	validates :name, presence: true
	validates :slug, presence: true, format: { with: /\A[a-zA-Z\-]+\z/, message: "can only have letters and -" }
	validates :status, presence: true

	def to_param
		slug
	end

	def self.current_id=(id)
    Thread.current[:group_id] = id
  end
  
  def self.current_id
    Thread.current[:group_id]
  end

	def year
		gift_time.strftime("%Y")
	end

	def self.create_matches
		logger.info "Starting to create matches for all open groups"
		count = 0
		open.each do |group|
			group.create_matches
			count += 1
	 	end
	 	logger.info "Finished creating matches for #{count} groups"
	end

	def create_matches
		logger.info "Starting to create matches for the #{self.name} group"
		users = User.available.where(group: self)
		count = 0
		if users.length > 2
			matches = loop do
	      shuffled = users.shuffle.zip(users.shuffle)
	      break shuffled if shuffled.index { |x,y| x == y } == nil
	    end
	    matches.each do |match|
	    	giver = match[0]
	    	receiver = match[1]
	    	Match.create(group: self, giver: giver, receiver: receiver)
				UserMailer.match_notification(giver, receiver).deliver_later
				count += 1
	    end
	    self.matched!
	  else
	  	print "Not enough available users in the #{group.name} group. Need at least 3."
	  end
	  logger.info "Finished creating #{count} matches the #{self.name} group"
	end

	def self.give_gifts
		logger.info "Starting to deliver gifts for all matched groups"
		count = 0
		Group.matched.each do |group|
			group.give_gifts
			count += 1
		end
		logger.info "Finished delivering gifts for #{count} groups"
	end

	def give_gifts
		logger.info "Starting to deliver gifts for the #{self.name} group"
		matches = Match.includes(:giver, :receiver).where(group_id: self.id)
		sent = 0
		missed = 0
		matches.each do |match|
			content = Content.find_by(match: match)
			if match.receiver && content && content.body
				content.given!
				UserMailer.send_gift(match.receiver, content, self).deliver_later
				sent += 1
			elsif match.receiver && match.giver
				UserMailer.no_gift_from_you(match.giver, match.receiver).deliver_later
				UserMailer.no_gift_for_you(match.receiver).deliver_later
				missed += 1
			end
		end
		self.gifted!
		logger.info "Finished #{sent} delivering gifts with #{missed} missing out for the #{self.name} group"
	end

	def draw_time
		if open?
			Group::MATCH_TIME
		elsif matched?
			Group::GIFT_TIME
		end
	end
end

app/controllers/elves/groups_controller.rb
class Elves::GroupsController < Elves::ElvesController

	def show
		@group = current_tenant
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.send(params[:filter]).includes(:giver, receiver_match: :content).order(:name)
		else
			@users = User.includes(:giver, receiver_match: :content).order(:name)
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  prepend_before_action :set_group
  
  def show
    if @group.open? || @group.closed?
      @users = User.available.order(created_at: :desc)
    elsif @group.matched? || @group.gifted?
      @users = User.playing.order(created_at: :desc)
    end
    if @group.gifted? || @group.closed?
      @content = Content.published
    end
  end

  def enquiry
    GroupMailer.enquiry(params[:group], params[:email]).deliver_later
  end

  private

    def set_group
      @current_tenant = @group = Group.find_by(slug: params[:id])
    end
end

app/controllers/santa/content_controller.rb
class Santa::ContentController < ApplicationController
  before_action :find_group_by_slug, only: [:index, :show, :edit, :update]
  before_action :find_content_by_token, only: [:show, :edit, :update]

  def index
    @content = Content.where(group: @group)
  end

  def show
  end

  def edit
  end

  def update
    unless !@content.update(content_params)
      flash_errors(@content)
    end
    redirect_to santa_group_content_path(@group, @content)
  end

  private

    def content_params
      params.require(:content).permit(:title, :url, :status)
    end

    def find_content_by_token
      @content = Content.find_by(token: params[:id])
    end

    def find_group_by_slug
      @group = Group.find_by(slug: params[:group_id])
    end
end

app/controllers/santa/groups_controller.rb
class Santa::GroupsController < Santa::SantaController
	skip_around_action :scope_current_tenant
	before_action :find_group_by_slug, only: [:show, :edit, :update]

	def index
		@groups = Group.includes(:users)
	end

	def show
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.send(params[:filter]).includes(:giver).where(group: @group).order(:name)
		else
			@users = User.includes(:giver).where(group: @group).order(:name)
		end
	end

	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			flash[:success] = "#{@group.name} has been created."
			redirect_to edit_santa_group_path(@group)
		else
			flash_errors(@group, true)
			puts flash.inspect
			render :new
		end
	end

	def edit
	end

	def update
		if @group.update(group_params)
			flash[:success] = "Those updates have been saved"
			redirect_to edit_santa_group_path(@group)
		else
			flash_errors(@group, true)
			puts flash.inspect
			render :edit
		end
	end

	private

		def find_group_by_slug
			@group = Group.find_by(slug: params[:id])
		end

		def group_params
			params.require(:group).permit(:name, :slug, :status)
		end
end

app/controllers/santa/messages_controller.rb
class Santa::MessagesController < Santa::SantaController

	def new
		@message = Message.new
	end

	def create
		@message = Message.new(message_params).deliver_later
		if @message.errors.full_messages.present?
			flash.now[:error] = @message.errors.full_messages.first
			render 'new'
		else
			flash[:success] = "Message was sent"
			redirect_to santa_root_path
		end
	end

	private

		def message_params
			params.require(:message).permit(:to, :subject, :body, :template)
		end
end

app/controllers/santa/santa_controller.rb
class Santa::SantaController < ApplicationController
	# layout 'santa'

	skip_before_action :authorize, :check_profile
	before_action :authorize_santa

	private 

		def authorize_santa
			deny_access unless current_user.santa?
		end

end

app/controllers/santa/users_controller.rb
class Santa::UsersController < Santa::SantaController
	before_action :find_user_by_token, only: [:show, :edit, :update]
	before_action :find_group_by_slug, only: [:assign, :set_assignments]

	def index
		if params[:filter] && User.valid_scope?(params[:filter])
			@users = User.unscoped.send(params[:filter]).includes(:group).order(:name)
		else
			@users = User.unscoped.includes(:group)
		end
	end

	def show
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "#{@user.name} has been created."
			redirect_to edit_user_path(@user)
		else
			flash_errors(@user, true)
			puts flash.inspect
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Those updates have been saved"
			redirect_to edit_user_path(@user)
		else
			flash_errors(@user, true)
			puts flash.inspect
			render :edit
		end
	end

	def assign
		if params[:search]
			@users = User.unscoped.includes(:group).where("name like :search or email like :search", search: "%#{params[:search]}%")
		end
	end

	def set_assignments
		@user = User.find_by(email: params[:email])
		if @user
			if @user.update(role: User.roles[:elf], group: @group)
				flash[:success] = "#{@user.name} has been elfed"
				UserMailer.made_elf(@user, @group).deliver_later
				redirect_to assign_santa_group_users_path(@group)
			else
				flash_errors(@user, true)
				render :assign
			end
		else
			flash[:success] = "An invite email has been sent to #{params[:email]}"
			UserMailer.invited_elf(params[:email], @group).deliver_later
			redirect_to assign_santa_group_users_path(@group)
		end
	end

	private

		def find_user_by_token
			@user = User.unscoped.find_by(token: params[:id])
		end

		def find_group_by_slug
			@group = Group.find_by(slug: params[:group_id] || params[:id])
		end

		def user_params
			params.require(:user).permit(:name, :slug)
		end
end

app/views/santa/groups/_form.html.erb
			<%= form_for [:santa, group] do |f| %>
				<fieldset>
					<div class="csw-form-group">
			  		<%= f.label :name, class: "csw-input-label" %>
			  		<%= f.text_field :name, class: "csw-form-input" %>
			  	</div>

			  	<div class="csw-form-group">
			  		<%= f.label :slug, class: "csw-input-label" %>
			  		<%= f.text_field :slug, class: "csw-form-input" %>
			    </div>

			    <div class="csw-form-group">
			  		<%= f.label :status, class: "csw-input-label" %>
							<%= f.select :status, Group.statuses.collect {|s| s[0] }, {prompt: 'Set the group status'}, class: "csw-form-input" %>
			    </div>

			  	<div class="csw-form-group">
						<%= f.submit "Save", class: "csw-button" %>
					</div>
				</fieldset>
			<% end %>

app/views/santa/groups/_group.html.erb
<div class="small-12 medium-6 large-4 columns">
	<h3><%= link_to group.name, santa_group_path(group) %></h3>
	<p>
		<strong>Users:</strong> <%= group.users.length %><br />
		<strong>Elves:</strong><br />
		<% group.users.elf.each do |elf| %>
			<%= link_to elf.name, elf %>
		<% end %>
	</p>
</div>

app/views/santa/groups/edit.html.erb
<% title "Edit #{@group.name}" %>

<div class="row">
	<div class="small-12 columns">
		<h1><%= yield :heading %></h1>
		<%= render "form", group: @group %>

		<h2>Elves</h2>
		<% @group.users.elf.each do |elf| %>
			<%= render "santa/users/elf", group: @group, elf: elf %>
		<% end %>
		<%= link_to "Add elf", assign_santa_group_users_path(group_id: @group), class: "csw-button" %>
	</div>
</div>

app/views/santa/groups/index.html.erb
<% title "List of groups" %>

<div class="row">
	<div class="small-12 columns">
		<h1><%= yield :heading %></h1>
		<p>
			<%= link_to "New group", new_santa_group_path, class: "csw-button" %>
			<%= link_to "New message", new_santa_message_path, class: "csw-button" %>
		</p>
		<%= render "santa/users/user_summaries", group_status: @groups.first.status %>
	</div>
</div>
<div class="row">
  <% @groups.each do |group| %>
  	<%= render "group", group: group %>
  <% end %>
</div>

app/views/santa/groups/new.html.erb
<% title "New group" %>

<div class="row">
	<div class="small-12 columns">
		<h1><%= yield :heading %></h1>
		<%= render "form", group: @group %>
	</div>
</div>

app/views/santa/groups/show.html.erb
<% title "#{@group.name}" %>

<div class="row">
	<div class="small-12 columns">
		<h1><%= yield :heading %></h1>
		<p>
			<%= link_to "Edit", edit_santa_group_path(@group), class: "csw-button csw-plain-button" %>
			<%= link_to "Content", santa_group_content_index_path(@group), class: "csw-button csw-plain-button" %>
		</p>
	</div>
</div>
<div class="row">
	<div class="small-12 columns">
	  <%= CountdownPresenter.new(@group, self).render_countdown %>
	  <% User.where(group: @group).scoping do %>
			<%= render "santa/users/user_summaries", group_status: @group.status %>
		<% end %>
		<div class="row csw-item-rows users">
      <% @users.each do |user| %>
      	<%= render "santa/users/user", user: user, group: @group %>
      <% end %>
    </div>
	</div>
</div>