config/routes.rb
Secretsanta::Application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "omniauth_callbacks" } 
  devise_scope :user do
    get "login", to: "devise/sessions#new", as: "login"
    delete "logout", to: "devise/sessions#destroy", as: "logout"
    get "signup", to: "users/registrations#new", as: "signup"
    resources :groups, path: "/", only: :none do
      get "signup", to: "users/registrations#new", as: "signup"
    end
  end

  get "about", to: "pages#about", as: :about
  get "tips", to: "pages#tips", as: :tips
  get "2013", to: "pages#blog_roll", as: :blog_roll
  get "run-group", to: "pages#run_group", as: :run_group
  get "open-groups", to: "pages#groups", as: :groups_page

  put "enquiry", to: "groups#enquiry", as: :enquiry_group

  
  namespace :santa do
    get "/", to: "groups#index", as: "root"
    resources :groups do
      resources :content, :matches
      resources :users, only: :none do
        collection do
          get "assign"
          put "set_assignments"
        end
      end
    end
    resources :users, only: [:show, :index]
    resources :messages, only: [:new, :create]
  end

  namespace :elves do
    get "/", to: "groups#show"
    # resources :content, only: [:index, :show, :edit, :update]
    resources :users do
      member do
        put "remove"
        put "replace"
        get "pull_out"
      end
    end
  end

  resources :groups, path: "/", only: :show do
    # get "/signup", to: "devise/registrations#new", as: "signup"
    resources :content, path: "gifts", only: [:show, :new, :edit, :update, :index] do
      member do
        put "edit", to: "content#update"
        put "send_gift"
        get "export"
        get "upload"
        patch "import"
        get "export"
        get "publish"
        put "save_publish"
      end
    end
  end
  resources :users

  root to: "pages#home"
end

app/models/content.rb
class Content < ActiveRecord::Base
  include Tokenfindable
	include Tenantable

	belongs_to :match

	scope :published, -> { given.where.not(url: '').order(updated_at: :desc) }

	validates :group_id, presence: true
	validates :url, format: { with: /\A(http|https):\/\/.+/, message: "must start with http:// or https://" }, allow_blank: true

	enum status: [ :draft, :ready, :given ]

	def import_file_contents(file)
    contents = read_file(file)
    self.body = contents if self.errors.empty?
  end

  def preview
    Kramdown::Document.new("# #{self.title}\n#{self.body}", auto_ids: false, smart_quotes: 'apos,apos,quot,quot').to_html
  end

  def published?
    given? && url.present?
  end

  private

  	def read_file(file)
      case File.extname(file.original_filename)
      when ".docx"
        begin
          html = Nokogiri::HTML(Docx::Document.open(file.path).to_html).at('body').inner_html.strip
          Kramdown::Document.new(html, input: 'html', smart_quotes: 'apos,apos,quot,quot').to_kramdown.gsub(/\\(['"])/, '\1')
        rescue
          self.errors.add(:file, "isn't a valid docx file and couldn't be imported.")
        end
      when ".md", ".markdown"
        begin
          File.open(file.path).read
        rescue
          self.errors.add(:file, "isn't a supported markdown file and couldn't be imported.")
        end
      else
        self.errors.add(:file, "isn't a supported file type and couldn't be imported.")
      end
    end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
  before_action :find_group_by_slug, only: [:new, :edit, :index, :show, :send_gift, :upload, :import, :export, :publish, :save_publish]
  before_action :find_content_by_token, only: [:edit, :show, :update, :send_gift, :upload, :import, :export, :publish, :save_publish]
  before_action :authorize_giver, only: [:edit, :send_gift, :upload, :import]
  before_action :authorize_receiver, only: [:show, :publish, :save_publish]
  skip_before_action :authenticate_user!, only: :index

  def new
    if @group.matched? || (@group.gifted? && (current_user.receiver_match.content.nil? || !current_user.receiver_match.content.given?))
      @content = Content.find_or_create_by(group_id: @group.id, match_id: current_user.receiver_match.id)
      redirect_to edit_group_content_path(@group, @content)
    else
      redirect_to root_path, message: "There doesn't seem to be a reason for you to create content. Am I wrong?"
    end
  end

  def index
    @content = Content.where(group: @group).published
  end

  def show
    redirect_to @group, notice: "Your gift is not ready yet. Check back later." unless @content.given?
  end

  def edit
    render 'show' if @content.given?
  end

  def update
    @content.update_attributes(content_params)
    respond_to do |format|
      if @content.save
        format.html { 
          flash[:success] = "You saved your content. Well, I saved it for you. All you did was click the button."
          redirect_to edit_group_content_path(@group, @content) 
        }
        format.js
        format.json { head :no_content }
      else
        format.html { render "show" }
        format.js
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def send_gift
    @receiver = current_user.receiver
    if @group && @receiver && @content && @content.body
      UserMailer.send_gift(@receiver, @content, @group).deliver_later
      @content.given!
      flash[:success] = "You're gift has been sent! Welcome back to the list of good children."
      redirect_to @group
    else
      puts "Starting..."
      puts @group
      puts @receiver
      puts @content
      flash[:error] = "That didn't work out. If your gift is ready and you're still seeing this message then get in touch with Santa."
      redirect_to edit_group_content_path(@group, @content)
    end
  end

  def import
    @content.import_file_contents(content_params[:body])
    if @content.errors.empty? && @content.save
      redirect_to edit_group_content_path(@group, @content)
    else
      flash_errors(@content)
      redirect_to edit_group_content_path(@group, @content)
    end
  end

  def upload
  end

  def export
    export_data = ExportPresenter.new(@content).render_content_for_export(params[:ext])
    if @content.errors.empty?
      send_data export_data[:output], filename: export_data[:filename], type: export_data[:type]
    else
      flash_errors(@content)
      redirect_to edit_group_content_path(@group, @content)
    end
  end

  def publish
  end

  def save_publish
    @first_publish = @content.url.nil?
    respond_to do |format|
      if @content.update(publish_params)
        UserMailer.published_gift(current_user.giver, current_user, @group).deliver_later if @first_publish
        format.html { 
          flash[:success] = "Your gift has been published for the world to see."
          redirect_to @group 
        }
        format.js
      else
        format.html do
          flash_errors(@content)
          render 'publish'
        end
        format.js
      end
    end
  end

  private

    def content_params
      params.require(:content).permit(:body, :title)
    end

    def publish_params
      params.require(:content).permit(:url)
    end

    def find_content_by_token
      @content = Content.find_by(token: params[:id])
    end

    def find_group_by_slug
      @group = Group.find_by(slug: params[:group_id])
    end

    def authorize_giver
      authorize_content(:giver)
    end

    def authorize_receiver
      authorize_content(:receiver)
    end

    def authorize_content(match_type)
      deny_access unless @content.match.send(match_type) == current_user
    end
end

app/controllers/santa/content_controller.rb
class Santa::ContentController < ApplicationController
  before_action :find_group_by_slug, only: [:index, :show, :edit, :update]
  before_action :find_content_by_token, only: [:show, :edit, :update]

  def index
    @content = Content.where(group: @group)
  end

  def show
  end

  def edit
  end

  def update
    unless !@content.update(content_params)
      flash_errors(@content)
    end
    redirect_to santa_group_content_path(@group, @content)
  end

  private

    def content_params
      params.require(:content).permit(:title, :url, :status)
    end

    def find_content_by_token
      @content = Content.find_by(token: params[:id])
    end

    def find_group_by_slug
      @group = Group.find_by(slug: params[:group_id])
    end
end

app/views/content/_content_actions.html.erb
      <div class="csw-content-sub-header csw-content-actions">
        <ul class="csw-content-actions-menu">
          <% if current_user.writer?(content) %>
            <li>
              <%= link_to upload_group_content_path(group, content), remote: true do %>
                <i class="csw-icon csw-icon-upload"></i> Import
              <% end %>
            </li>
          <% end %>
          <li>
            <a class="csw-dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="csw-icon csw-icon-share"></i> Export <span class="csw-caret"></span>
            </a>
            <ul class="csw-dropdown-menu" role="menu">
              <li><%= link_to "as HTML", export_group_content_path(group, content, ext: "html"), target: "_blank" %></li>
              <li><%= link_to "as Markdown", export_group_content_path(group, content, ext: "markdown"), target: "_blank" %></li>
              <li><%= link_to "as plain text", export_group_content_path(group, content, ext: "text"), target: "_blank" %></li>
            </ul>
          </li>
          <% if current_user.writer?(content) %>
            <li>
              <%= button_tag type: "submit", class: "csw-button csw-text-button", id: "save-content" do %>
                <i class="csw-icon csw-icon-save"></i> <span class="csw-save-text">Saved</span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

app/views/content/_content_actions_edit.html.erb
      <div class="csw-content-sub-header csw-content-actions">
        <div class="csw-content-actions-left">
          <ul class="csw-content-actions-menu">
            <% if current_user.writer?(content) %>
              <li>
                <%= link_to upload_group_content_path(group, content), remote: true do %>
                  <i class="csw-icon csw-icon-upload"></i> Import
                <% end %>
              </li>
            <% end %>
            <li>
              <a class="csw-dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="csw-icon csw-icon-share"></i> Export <span class="csw-caret"></span>
              </a>
              <ul class="csw-dropdown-menu" role="menu">
                <li><%= link_to "as HTML", export_group_content_path(group, content, ext: "html"), target: "_blank" %></li>
                <li><%= link_to "as Markdown", export_group_content_path(group, content, ext: "markdown"), target: "_blank" %></li>
                <li><%= link_to "as plain text", export_group_content_path(group, content, ext: "text"), target: "_blank" %></li>
              </ul>
            </li>
            <% if current_user.writer?(content) %>
              <li>
                <%= button_tag type: "submit", class: "csw-button csw-text-button", id: "save-content" do %>
                  <i class="csw-icon csw-icon-save"></i> <span class="csw-save-text">Save</span>
                <% end %>
              </li>
            <% end %>
            <% if @group.gifted? %>
              <li class="csw-pull-right">
                <%= link_to send_gift_group_content_path(@group, @content), class: "csw-font-green",  method: :put do %>
                  <i class="csw-icon csw-icon-paperplane"></i> Send gift
                <% end %>
              </li>
          <% end %>
          </ul>
        </div>

        <div class="csw-content-actions-right">
          <ul class="csw-tabs csw-content-right-tabs">
            <li class="csw-tab-active">
              <%= link_to "#mde-tab-formatted", data: { toggle: "tab" } do %>
                <i class="csw-icon csw-icon-font"></i> Formatted preview
              <% end %>
            </li>
            <li>
              <%= link_to "#mde-tab-html", data: { toggle: "tab" } do %>
                <i class="csw-icon csw-icon-code"></i> HTML preview
              <% end %>
            </li>
            <li>
              <%= link_to "#mde-tab-markdown-reference", data: { toggle: "tab" } do %>
                <i class="csw-icon csw-icon-question-circle"></i> Markdown reference
              <% end %>
            </li>
          </ul>
        </div>
      </div>

app/views/content/_content_published.html.erb
							<li>
                <h2><%= link_to content.title, content.url, target: "_blank" %></h2>
                <p>on <%= link_to host_only(content.url), "http://" << host_only(content.url), target: "_blank" %>
                <p>
                  <%= prepare_snippet(content.body) %> 
                  <%= link_to "Read post", content.url, target: "_blank" %>
                </p>
              </li>

app/views/content/_late_delivery.html.erb
													<div class='csw-modal-body'>
														<p>Don't worry, you can still send your gift when you're ready. Simple write it or import it and then click the "Send gift" link (top left). I'll deliver it immediately to <%= current_user.receiver.name %>.</p>
													</div>
													<div class="csw-modal-footer">
													  <a href="#" class="csw-button csw-plain-button" data-dismiss="modal" aria-hidden="true">Close</a>
													</div>

app/views/content/_publish_confirm.html.erb
<div class="csw-modal-body">
<i class="csw-icon csw-icon-paperplane csw-font-green csw-icon-giant"></i>
<% if content.url.blank? %>
	<h2 class="csw-finished-heading">Okay. Your gift isn't published.</h2>
	<p>For a gift to be published it has to have a URL linking to where you posted it on your blog. Your gift is not on the <%= link_to "#{group.name} group blogroll", group_content_index_path(group) %>. You can still check out the other gifts as they go live.</p>
<% elsif first_publish %>
	<h2 class="csw-finished-heading">Nice! Your gift is now published!</h2>
	<p>Your gift has been added to the <%= link_to "#{group.name} group blogroll", group_content_index_path(group) %>. Check out the other gifts as they go live.</p>
<% else %>
	<h2 class="csw-finished-heading">Nice! The URL for your gift is updated.</h2>
	<p>The updated URL will now show on the <%= link_to "#{group.name} group blogroll", group_content_index_path(group) %>. Check out the other gifts as they go live.</p>
<% end %>
</div>

app/views/content/_publish_form.html.erb
      <%= form_for @content, url: save_publish_group_content_path(@group, @content), method: :put, remote: true do |f| %>
        <div class="csw-modal-body">
          <div class="csw-form-group">
            <%= f.label :url, "URL to your gift post", class: "csw-input-label" %>
            <%= f.text_field :url, class: "csw-form-input", placeholder: "Enter the URL for your published gift post" %>
          </div>
        </div>
        <div class="csw-modal-footer">
          <a href="#" class="csw-button csw-plain-button" data-dismiss="modal" aria-hidden="true">Close</a>
          <%= f.submit "Save", class: "csw-button" %>
        </div>
      <% end %>

app/views/content/_upload_form.html.erb
					<%= form_for @content, url: import_group_content_path(@group, @content) do |f| %>            
            <div class="csw-modal-body">
              <p>Select .docx or markdown file you want to upload. <strong>This will overwrite the content.</strong></p>
              <div class="csw-input-group">
              	<span class="csw-input-group-button">
	                <span class="csw-button csw-button-file">
	    							Browse&hellip; <%= f.file_field :body %>
									</span>
								</span>
								<%= text_field_tag :file, nil, class: "csw-form-input", readonly: true %>
              </div>
            </div>
            <div class="csw-modal-footer">
              <a href="#" class="csw-button csw-plain-button" data-dismiss="modal" aria-hidden="true">Close</a>
              <%= f.submit "Import", name: "modal", class: "csw-button" %>
            </div>
          <% end %>

app/views/content/index.html.erb
 <% title "#{@group.name} 2014 blogroll" %>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="content narrow">
        <h1><%= yield :heading %></h1>
        <% if @group.gifted? %>
          <p>Check back regularly to see new posts!</p>
        <% else %>
          <p>Thanks to everyone who wrote these gift posts!</p>
        <% end %>
        <% if @content.present? %>
          <ul class="all_content">
            <% @content.each do |content| %>
              <%= render "content_published", content: content %>
            <% end %>
          </ul>
        <% else %>
          <p>Check back soon.</p>
        <% end %>
      </div>
    </div>     
  </div>
</div>

app/views/content/publish.js.erb
$('body').append('<%=j render 'layouts/modal' %>');
$('#csw-modal-window').modal('show');
$('.csw-modal-main-wrapper').html('<%=j render 'publish_form' %>');
$('.csw-modal-title').html("List your gift");

app/views/content/save_publish.js.erb
$('.csw-alert').remove();
<% if @content.errors.any? %>
	<% @content.errors.full_messages.each do |message| %>
		<% flash.now[:error] = message %>
		$('.csw-modal-body').prepend('<%=j render 'layouts/flash', flash: flash %>');
	<% end %>
<% else %>
	$('.csw-modal-main-wrapper').fadeOut(200, function(){
		$('.csw-modal-main-wrapper').html('<%=j render 'content/publish_confirm', group: @group, first_publish: @first_publish, content: @content %>').fadeIn(200);
		$('.csw-modal-title').html("&nbsp;");
		$('.csw-publish-url-button').html('<i class="csw-icon csw-icon-paperplane"></i> Edit the published URL');
	});
<% end %>

app/views/content/show.html.erb
<% title "#{@content.title}" %>

			<div class="csw-content-sub-header csw-content-actions">
        <ul class="csw-content-actions-menu">
          <li>
            <a class="csw-dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="csw-icon csw-icon-share"></i> Export <span class="csw-caret"></span>
            </a>
            <ul class="csw-dropdown-menu" role="menu">
              <li><%= link_to "as HTML", export_group_content_path(@group, @content, ext: "html"), target: "_blank" %></li>
              <li><%= link_to "as Markdown", export_group_content_path(@group, @content, ext: "markdown"), target: "_blank" %></li>
              <li><%= link_to "as plain text", export_group_content_path(@group, @content, ext: "text"), target: "_blank" %></li>
            </ul>
          </li>
          <li>
          	<a class="csw-html-toggle" href="#">
          		<i class="csw-icon csw-icon-code"></i> Show HTML
          	</a>
          </li>
          <li>
            <%= link_to publish_group_content_path(@group, @content), class: "csw-publish-url-button", remote: true do %>
              <i class="csw-icon csw-icon-paperplane"></i> <%= @content.url.blank? ? "Publish your gift" : "Edit the published URL" %>
            <% end %>
          </li>
        </ul>
      </div>
    	<div class="csw-content-plain-preview csw-tab-content">
	      <div class="csw-tab-pane csw-tab-active" id="mde-tab-formatted">
          <div class="mde-preview"><%= raw @content_preview %></div>
        </div>
        <div class="csw-tab-pane" id="mde-tab-html">
          <xmp class="mde-html"><%= raw @content_preview %></xmp>
        </div>
	    </div>

app/views/content/update.js.erb
$(".alert").remove();
<% if @content.errors.any? %>
	<% @content.errors.full_messages.each do |message| %>
		<% flash.now[:error] = message %>
		$('.main-wrapper').prepend('<%=j render 'layouts/flash', flash: flash %>');
	<% end %>
<% else %>
	window.editor.successfulSave();
<% end %>

app/views/content/upload.js.erb
$('body').append('<%=j render 'layouts/modal' %>');
$('#csw-modal-window').modal('show');
$('.csw-modal-main-wrapper').html('<%=j render "upload_form" %>');
$('.csw-modal-title').html("Upload");